sonar.projectKey=eldirohmanur_parkeer
sonar.organization=eldirohmanur
sonar.projectName=Parkeer
sonar.projectVersion=1.0.0

sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main,core/*/src/main,feature/*/src/main
sonar.tests=app/src/test,core/*/src/test,feature/*/src/test
sonar.sourceEncoding=UTF-8

sonar.android.lint.reportPaths=app/build/reports/lint-results-debug.xml
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/kover/reportDebug.xml

sonar.kotlin.detekt.reportPaths=build/reports/detekt/detekt.xml
sonar.exclusions=**/build/**,**/*.json,**/test/**
