sonar.projectKey=eldirohmanur_parkeer
sonar.organization=eldirohmanur
sonar.projectName=Parkeer
sonar.projectVersion=1.0.0

sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java,core/model/src/main/java,core/nfc/src/main/java,core/crypto/src/main/java,core/cardprotocol/src/main/java,core/ui/src/main/java,core/firebase/src/main/java,feature/station/src/main/java,feature/gate/src/main/java,feature/terminal/src/main/java,feature/scout/src/main/java
sonar.tests=feature/terminal/src/test/java,core/cardprotocol/src/test/java
sonar.sourceEncoding=UTF-8

sonar.android.lint.reportPaths=app/build/reports/lint-results-debug.xml
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/kover/reportDebug.xml

sonar.kotlin.detekt.reportPaths=build/reports/detekt/detekt.xml
sonar.exclusions=**/build/**,**/*.json,**/test/**
